#!/bin/bash

OLD_STTY=$(stty -g)

function cleanup {
    stty "$OLD_STTY"
    exit $1
}

trap cleanup SIGHUP SIGINT SIGTERM

make _pc4th >/dev/null

if [ $? -eq 0 ]; then
    stty cbreak
    stty -echo
    stty -icrnl

    if [ "$1" == "" ]; then
        ./_pc4th
    else
        ./_pc4th < $1
    fi
fi

cleanup $?
