#!/bin/bash

make _pc4th >/dev/null && (
    OLD_STTY=$(stty -g)
    stty cbreak
    stty -echo
    stty -icrnl

    if [ "$1" == "" ]; then
        ./_pc4th
    else
        ./_pc4th < $1
    fi

    stty "$OLD_STTY"
    )
